defaults:
  - safety_gym_base

task_name: go_to_goal
task_params: {}

train_params:
  damping:
    x: [1., 1.]
    y: [1., 1.]
    z: [1., 1.]
  gear:
    x: [-0.2, 0.2]
    z: [-0.1, 0.1]
  mass: [1., 1.]

eval_params:
  damping:
    x: [0.3, 1.]
    y: [0.3, 1.]
    z: [0.7, 1.0]
  gear:
    x: [0., 0.2]
    z: [0., 0.1]
  mass: [1., 1.10]
