defaults:
  - brax_base
  - _self_

backend: mjx
task_name: humanoid_safe

# Sample uniformly around the nominal value
train_params:
  mass: [0., 1.] # mass of the pole, not cart.
  gear: [5., 20.]

eval_params:
  mass: [0., 1.]
  gear: [5., 20.]
