defaults:
  - _self_
  - train_car_params: car_2_blend
  - eval_car_params: car_2_blend

domain_name: rccar
task_name: rccar
dt: 0.033
encode_angle: true
ctrl_cost_weight: 0.005
margin_factor: 20.0
max_throttle: 0.4
use_obs_noise: false
obstacles:
  - [0.75, -0.81, 0.15]
  - [0.75, -0.54, 0.15]
  - [0.75, -0.27, 0.15]
  - [0.75, 0.0, 0.15]
  - [0.75, 0.27, 0.15]
  - [0.75, 0.54, 0.15]
  - [0.75, 0.81, 0.15]
observation_delay: 0
action_delay: 0
sliding_window: 0
sample_init_pose: true
