nominal:
  use_blend: 1.0
  m: 1.65
  l_f: 0.13
  l_r: 0.17
  angle_offset: 0.0
  b_f: 2.75
  b_r: 5.0
  blend_ratio_lb: 0.001
  blend_ratio_ub: 0.017
  c_d: 0.0
  c_f: 1.45
  c_m_1: 8.2
  c_m_2: 1.25
  c_r: 1.3
  d_f: 0.4
  d_r: 0.3
  i_com: 0.06
  steering_limit: 0.6